### ISSUE TITLE
bug: MediaContainerResource has no unit tests and has broken transmogrify path

### ISSUE THREAD

**Issue by jzacsh** [google/data-transfer-project#1058]
background context: in the process of doing other work on the media vertical I needed to add unit tests for my own new code in `MediaContainerResource`

In doing that, I found that `MediaContainerResource` _itself_ didn't have any tests, so nowhere to add test coverage for my new code. However since it was was forked from `PhotoContainerResource` porting the tests should be trivial (at least to get baseline coverage for _majority_ of the forked logic), so I'm doing that as part of this bug to get the ball rolling here and unblock myself.

Tasks I'm tackling as part of this issue:
- [x] obvz, backfill the unit test of `MediaContainerResource`; original unit test is [PhotosContainerResourceTest]
- [x] fix new bug test backfilling discovered: we had a hidden runtime exception[^1]: we were trying to rewrite 
- [x] other less urgent things but takes 2sec to cleanup while I'm passing through
  - [x] [ensureCleanAlbumNames] should be private
  - [x] [ensureRootAlbum] doc is wrong and in fixing that might as well simplify that func (let the func do one thing; eg: not worry about boolean parameters)
  - ~~[ ] [skipping this] #1060~~

[ensureCleanAlbumNames]: https://github.com/google/data-transfer-project/blob/2597c2b418c9b47d9a2e7403983f5c293fd77cb8/portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java#L168
[ensureRootAlbum]: https://github.com/google/data-transfer-project/blob/2597c2b418c9b47d9a2e7403983f5c293fd77cb8/portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java#L142

[^1]: _("hidden" in that nothing was catching it, but it was there just waiting to be executed and thrown)_ runtime exception due to [rewriting `final ... album` field][forkedAppendAlbum] pasted below for reference; compare to [the original implementation that was forked, here][origAppendAlbum]:
    ```none
    verifyTransmogrifyAlbums_NoRootPhotos
    java.lang.UnsupportedOperationException
        at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:228)
        at org.datatransferproject.types.common.models.media.MediaContainerResource.ensureRootAlbum(MediaContainerResource.java:132)
        at org.datatransferproject.types.common.models.media.MediaContainerResource.transmogrify(MediaContainerResource.java:72)
        at org.datatransferproject.types.common.models.media.MediaContainerResourceTest.verifyTransmogrifyAlbums_NoRootPhotos(MediaContainerResourceTest.java:108)
    ```

[PhotosContainerResourceTest]: https://github.com/google/data-transfer-project/blob/2597c2b418c9b47d9a2e7403983f5c293fd77cb8/portability-types-common/src/test/java/org/datatransferproject/types/common/models/photos/PhotosContainerResourceTest.java
[forkedAppendAlbum]: https://github.com/google/data-transfer-project/blob/2597c2b418c9b47d9a2e7403983f5c293fd77cb8/portability-types-common/src/main/java/org/datatransferproject/types/common/models/media/MediaContainerResource.java#L131
[origAppendAlbum]: https://github.com/google/data-transfer-project/blob/2597c2b418c9b47d9a2e7403983f5c293fd77cb8/portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java#L160-L164

**Comment by jzacsh** [comment]
(decided to punt the last detail to #1060)
