### ISSUE TITLE
Travis fails on master when we merge

### ISSUE THREAD

**Issue by rtannenbaum** [google/data-transfer-project#504]
Our builds on master have been failing https://travis-ci.org/google/data-transfer-project/builds

The builds on the PRs have succeeded, before merging to master

We seem to have lost a bunch of build history on Travis (or don't retain it) past 7 days ago, but it does show up for 6+ months ago. So hard to say when this started happening but it seems like it could be related to the new dockerhub push in https://github.com/google/data-transfer-project/pull/474

**Comment by rtannenbaum** [comment]
I think https://github.com/google/data-transfer-project/commit/1808a91f757996d3334e4ceb6754eff58e6cb471 may fix it actually, it might not have run on the last merge to master

The log from the last fail on master shows:
Deploying application
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Node installation: local, Cloud type: local
:client-rest:nodeSetup SKIPPED
:client-rest:buildLocalWebAppmodule.js:538
    throw err;
    ^
Error: Cannot find module '/home/travis/build/google/data-transfer-project/client-rest/node_modules/.bin/ng'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':client-rest:buildLocalWebApp'.
> Process 'command 'node'' finished with non-zero exit value 1
