### ISSUE TITLE
NPE in PortabilityInMemoryDataCopier

### ISSUE THREAD

**Issue by rtannenbaum** [google/data-transfer-project#551]
[2018-08-17 15:58:59,489] [undefined]: DEBUG - Polled job 190c3741-4d88-4c33-bc9a-17b7ef833da9
[2018-08-17 15:59:00,515] [190c37414d884c33]: DEBUG - Updated job 190c3741-4d88-4c33-bc9a-17b7ef833da9 to CREDS_ENCRYPTION_KEY_GENERATED, publicKey length: 162
[2018-08-17 15:59:20,587] [190c37414d884c33]: DEBUG - Polled job 190c3741-4d88-4c33-bc9a-17b7ef833da9 in state CREDS_ENCRYPTED
[2018-08-17 15:59:20,589] [190c37414d884c33]: DEBUG - Polled job 190c3741-4d88-4c33-bc9a-17b7ef833da9 has auth data as expected. Done polling.
[2018-08-17 15:59:20,591] [190c37414d884c33]: DEBUG - Begin processing jobId: 190c3741-4d88-4c33-bc9a-17b7ef833da9
[2018-08-17 15:59:20,681] [190c37414d884c33]: DEBUG - Starting copy job, id: 190c3741-4d88-4c33-bc9a-17b7ef833da9, source: FLICKR, destination: GOOGLE
[2018-08-17 15:59:21,031] [190c37414d884c33]: DEBUG - Job 190c3741-4d88-4c33-bc9a-17b7ef833da9: copy iteration: 1
[2018-08-17 15:59:21,032] [190c37414d884c33]: DEBUG - Job 190c3741-4d88-4c33-bc9a-17b7ef833da9: Starting export
Aug 17, 2018 3:59:21 PM com.google.common.util.concurrent.UncaughtExceptionHandlers$Exiter uncaughtException
SEVERE: Caught an exception in Thread[main,5,main].  Shutting down.
java.lang.NullPointerException
	at org.datatransferproject.types.transfer.retry.RetryingCallable.call(RetryingCallable.java:65)
	at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copyHelper(PortabilityInMemoryDataCopier.java:110)
	at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copy(PortabilityInMemoryDataCopier.java:75)
	at org.datatransferproject.transfer.JobProcessor.processJob(JobProcessor.java:112)
	at org.datatransferproject.transfer.Worker.doWork(Worker.java:33)
	at org.datatransferproject.transfer.WorkerMain.poll(WorkerMain.java:136)
	at org.datatransferproject.transfer.WorkerMain.main(WorkerMain.java:56)

**Comment by calumcalder** [comment]
There's been some refactoring on `DataCopier` classes since this was raised, so I'm going to assume it's been fixed and close out this issue
