### ISSUE TITLE
HttpResponseException: 429 Too Many Requests (for GooglePhotosImporter)

### ISSUE THREAD

**Issue by natlg** [google/data-transfer-project#651]
Tested with 10 albums, could import all albums but fails in few photos.
Also happens if try to import more then 40 albums, even with paged export.

API guide suggests to implement exponential backoff
https://developers.google.com/drive/api/v3/handle-errors#exponential-backoff

```
com.google.api.client.http.HttpResponseException: 429 Too Many Requests
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'photoslibrary.googleapis.com/write_requests' and limit 'WritesPerMinutePerUser' of service 'photoslibrary.googleapis.com' for consumer 'project_number:598947737466'.",
    "errors": [
      {
        "message": "Quota exceeded for quota metric 'photoslibrary.googleapis.com/write_requests' and limit 'WritesPerMinutePerUser' of service 'photoslibrary.googleapis.com' for consumer 'project_number:598947737466'.",
        "domain": "global",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "RESOURCE_EXHAUSTED"
  }
}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1072)
	at org.datatransferproject.datatransfer.google.photos.GooglePhotosInterface.makePostRequest(GooglePhotosInterface.java:162)
	at org.datatransferproject.datatransfer.google.photos.GooglePhotosInterface.createAlbum(GooglePhotosInterface.java:116)
	at org.datatransferproject.datatransfer.google.photos.GooglePhotosImporter.importSingleAlbum(GooglePhotosImporter.java:107)
	at org.datatransferproject.datatransfer.google.photos.GooglePhotosImporter.importItem(GooglePhotosImporter.java:86)
	at org.datatransferproject.datatransfer.google.photos.GooglePhotosImporter.importItem(GooglePhotosImporter.java:42)
	at org.datatransferproject.transfer.CallableImporter.call(CallableImporter.java:48)
	at org.datatransferproject.transfer.CallableImporter.call(CallableImporter.java:30)
	at org.datatransferproject.types.transfer.retry.RetryingCallable.call(RetryingCallable.java:66)
	at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copyHelper(PortabilityInMemoryDataCopier.java:121)
	at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copyHelper(PortabilityInMemoryDataCopier.java:140)
	at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copyHelper(PortabilityInMemoryDataCopier.java:140)
	at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copyHelper(PortabilityInMemoryDataCopier.java:140)
	at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copy(PortabilityInMemoryDataCopier.java:71)
	at org.datatransferproject.transfer.JobProcessor.processJob(JobProcessor.java:111)
	at org.datatransferproject.transfer.Worker.doWork(Worker.java:33)
	at org.datatransferproject.transfer.WorkerMain.poll(WorkerMain.java:142)
	at org.datatransferproject.bootstrap.vm.SingleVMMain$WorkerRunner.run(SingleVMMain.java:109)
..
```

**Comment by lisad** [comment]
Reliability issues will always be with us and sometimes quota errors are the correct response.  That said, this probably requires some documentation - writing down for adapter programmers what can be done next about 529 errors, (e.g. backing off request rates, when to retry, etc)

**Comment by lisad** [comment]
Meta has also experienced this problem transfering photos from Meta to Google. Needs more investigation

**Comment by lisad** [comment]
Please reopen this issue if there are 429 errors that recur in cases where there ought to be enough quota - we'll need a fresh report in order to investigate if this is still happening as many systems have changed since this issue's stack trace, and 429 errors are not common in logs recently.
